### PR TITLE
Added forgot Password route

### PR DESCRIPTION
**Pull request by Sourabh782**
Implemented forgot password route in backend.

Resolves issue: #1 

1. Register with old password
register old

2. forgot password route
forget password

3. Retrying login with old password ( Resulting in failed )
password changed

4. using new password to login
newPasswordlogin

Tried self tests,

new code snippet: 
Screenshot 2024-10-01 205605

### CODE REVIEW

**Comment by 10kumaranurag01** [comment]
@Sourabh782  You should be returning when ever the route reaaches an error for e.g

 return res.status(401).json({ message: 'Invalid credentials' });

 return res.status(400).json({ message: error.errors || 'Invalid data' });

**Comment by Sourabh782** [comment]
@10kumaranurag01 actually You didnt returned originally so i skipped that, shold i add this to all routes?
Screenshot 2024-10-01 221750

**Comment by 10kumaranurag01** [comment]
@Sourabh782 Ya do it for all routes

**Comment by Sourabh782** [comment]
Sure @10kumaranurag01  on it

**Comment by 10kumaranurag01** [comment]
Am closing this PR, make the changes, create a new PR and i will review it.

**Comment by Sourabh782** [comment]
@10kumaranurag01 sure

**Pull request closed without merging**
